nacos:
  config:
#    password: nacos
#    username: nacos
#    group: OTHER_GROUP
#    data-id: demo.yml
    server-addr: 127.0.0.1:8848
    auto-refresh: true
    group: DEFAULT_GROUP

#swagger:
#  docket:
#    base-package: io
