spring:
  application:
    name: grpc-client


grpc:
  client:
    grpc-server:
      address: "static://localhost:10000"
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext
server:
  port: 8999
swagger:
  docket:
    base-package: io.wilson.grpc