spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: tiger
    username: root
    url: jdbc:mysql://localhost:3306/wilson?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    name: db-test
  http:
    converters:
      preferred-json-mapper: jackson
  profiles:
    active: dev
  common:
    validation:
      msg-locale: zh_CN
  application:
    name: test

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
swagger:
  docket:
    base-package: io.github.test.controller



